-- list of softwares to install

liste_softs = {
   "amixer",
   "ansiweather",
   "blueman-applet",
   "chromium",
   "darktable",
   "emacs",
   "firefox",
   "gftp",
   "gsimplecal",
   "google-play-music-desktop-player",
   "i3lock",
   "import",
   "keepassxc",
   "mpd",
   "nautilus",
   "nm-applet",
   "opera-developer",
   -- "pacmd",
   -- "pactl",
   -- "phototonic",
   "python3",
   "rivalcfg",
   "synaptic",
   "thunar",
   "tyrfingcolor",
   "urxvtd",
   "wget",
   "wish8.6",
   "xcompmgr",
   "xgamma",
   "xrandr",
   "xterm"
}
